# Force Railway to use Node.js instead of staticfile detection
[providers]
nodejs = "18"

[phases.build]
cmds = ["npm install --production"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"